repos:
  - repo: local
    hooks:
      - id: opa-fmt
        name: Format OPA policies
        entry: make
        args: [fmt]
        language: system
        files: \.rego$
        pass_filenames: false
        always_run: false
      - id: opa-test
        name: Run OPA tests
        entry: make
        args: [test]
        language: system
        files: ^opa/
        pass_filenames: false
        always_run: false