services:
  trino:
    image: trinodb/trino:latest
    container_name: trino
    ports:
      - "8080:8080"
    volumes:
      - ./trino/etc:/etc/trino
      - ./trino/data:/data/trino

  cloudbeaver:
    image: dbeaver/cloudbeaver:latest
    container_name: cloudbeaver
    ports:
      - "8978:8978"
    volumes:
      - ./cloudbeaver/workspace:/opt/cloudbeaver/workspace
    depends_on:
      - trino

  opa:
    image: openpolicyagent/opa:0.69.0
    container_name: opa
    ports:
      - "8181:8181"
    command: ["run", "--server", "--addr", "0.0.0.0:8181", "--config-file", "/config.yaml", "--log-level", "debug", "/policy", "/data"]
    volumes:
      - ./opa/policies:/policy
      - ./opa/data:/data
      - ./opa/config.yaml:/config.yaml

  opa-test:
    image: openpolicyagent/opa:0.69.0
    command: ["test", "-v", "/tests"]
    volumes:
      - ./opa/tests:/tests
      - ./opa/policies:/policies
      - ./opa/data:/data
    profiles:
      - tools

  opa-test-file:
    image: openpolicyagent/opa:0.69.0
    entrypoint: ["opa"]
    volumes:
      - ./opa/tests:/tests
      - ./opa/policies:/policies
      - ./opa/data:/data
    profiles:
      - tools
